export const CHANGE_CURRENT_ALBUM = 'album/CHANGE_CURRENT_ALBUM';
export const CHANGE_PULLUP_LOADING = 'album/CHANGE_PULLUP_LOADING';
export const CHANGE_ENTER_LOADING = 'album/CHANGE_ENTER_LOADING';
export const CHANGE_START_INDEX = 'album/CHANGE_START_INDEX';
export const CHANGE_TOTAL_COUNT = 'album/CHANGE_TOTAL_COUNT';
